spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9095

  datasource:
    url: jdbc:mysql://localhost:3308/productservice

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
